### ISSUE TITLE
Tricky bug with ALIASES

### ISSUE THREAD

**Issue by xfra35** [bcosca/fatfree-core#118]
I can't believe that one slipped through:
```php
$f3->route('GET @blog: /blog/@id','Blog->get');
$f3->PARAMS=array('id'=>1);
print_r($f3->ALIASES);// Array ( [blog] => /blog/1 ) !!!!!
echo $f3->alias('blog','id=3');// /blog/1 Ooops..
```
Looks like [this line](https://github.com/bcosca/fatfree-core/blob/cdd499e16683a9cbdf2d0915cf0b680a7ef98196/base.php#L288) is guilty. It's trying to automatically build aliases.

What was the intention? Can we drop this line?

The tricky part of this bug is that `alias()` behaves normally until we specifically call `$f3->ALIASES` (not `$f3->get('ALIASES')`) on a route **containing tokens**. I believe that this is due to the fact that `$f3->ALIASES` returns a reference while `$f3->get('ALIASES')` doesn't.

**Comment by ikkez** [comment]
Hi xfra35. Yes I think this is just a part for backward compatibility to the initial v3.3 solution. I crawled through the old alias issues, because I had in mind that there was something left and found this something in https://github.com/bcosca/fatfree/pull/720:

> [...], because the main problem is that this line [...] is nice for having pre-filled alias routes, but also takes the chance of changing the tokens to something else afterwards, because they would already be replaced if your current route contains parameters that are also used in the alias route.

I'm pretty sure that I was referring to that same line you mean too, which was already superfluous with the time of that enhancement. So I think we can safely remove that part.

**Comment by xfra35** [comment]
Well spotted! That looks indeed like a remnant of the past. I'll remove it.
