### ISSUE TITLE
Why does '<?' work with Template::instance()->render ?

### ISSUE THREAD

**Issue by trenchcode** [bcosca/fatfree-core#133]
Why do `<?` short tags work in template files, while the `<?php` and `<?=` tags don't when using:
`echo \Template::instance()->render('template.htm');`

This behaviour is unexpected, looking at the [docs](http://fatfreeframework.com/views-and-templates).

**Comment by ikkez** [comment]
Because `<?` is not safe to use as php open tag. It's also used by the XML syntax, i.e. `<?xml version="1.0" encoding="UTF-8" ?>` and would otherwise cause some malfunction.

**Comment by geniuswebtools** [comment]
From the manual:
http://php.net/manual/en/language.basic-syntax.phptags.php

> PHP also allows for short open tag <? (which is discouraged since it is only available if enabled using the short_open_tag php.ini configuration file directive, or if PHP was configured with the --enable-short-tags option).

**Comment by trenchcode** [comment]
I know about the risks, but code in `<?` tags does work in F3 templates. 

What I am trying to understand is this: In terms of functionality, `<?` and `<?php` are identical. So why does one work in F3 templates, while the other doesn't?

**Comment by ikkez** [comment]
Because it is not allowed to put `<?php` code into templates.. that's why you are using a template engine.. you should not put plain php tags into it. The render method strips it out.

**Comment by trenchcode** [comment]
The reason why `<?` is allowed is... because the render method cannot strip it without stripping XML code?

**Comment by ikkez** [comment]
I think yes. But another problem is, that in case you have a XML template, you cannot include that pre-compiled template with shorttags enabled, because the php interpreter would eval `<?xml` as php, which leads to undefined constant errors. So a workaround is mandatory nevertheless. So actually I'm not 100% sure about `<?`. [This code](https://github.com/bcosca/fatfree-core/blob/master/base.php#L2680-L2683) was there since the first commit.

**Comment by ikkez** [comment]
can we close this, or is there any issue with it?

**Comment by ikkez** [comment]
reviewed and fixed now.
