### ISSUE TITLE
Little bug in Markdown class

### ISSUE THREAD

**Issue by xfra35** [bcosca/fatfree-core#136]
Bug encountered while editing [this block](http://fatfreeframework.com/quick-reference#PREFIX).

<ul>
<li><code>`$f3->get('DICT.hello')` if `PREFIX=DICT.`</code> => OK</li>
<li><code>`$f3->get('DICT_hello')` if `PREFIX=DICT_`</code> => not working</li>
</ul>

I've narrowed it down to this:
<ul>
<li><code>`foo_bar_baz`</code> => <code>&lt;p&gt;&lt;code&gt;foo_bar_baz&lt;/code&gt;&lt;/p&gt;</code></li>
<li><code>`foo_bar_`</code> => <code>&lt;p&gt;&lt;code&gt;foo&amp;lt;em&amp;gt;bar&amp;lt;/em&amp;gt;&lt;/code&gt;&lt;/p&gt;</code></li>
</ul>

So the trailing underscore seems to trigger the bug.

**Comment by sn0opy** [comment]
Sent a PR to fix this issue for now. Eventhough I'm not really lucky with it, since it shouldn't be processed anyway. Content in code tags should neither get escaped nor processed by the class. Unfortunately, this probably requires some further changes in the `scan()` function in the Markdown class to stop processing if the `code` tag has been found in the string.
