### ISSUE TITLE
TODO: remove

### ISSUE THREAD

**Issue by stehlo** [bcosca/fatfree-core#214]
As mentioned previously, I have had enough.

For those who were genuinely interested in resolving the original issue stated in this place:

Don't worry, be happy. [Avatar Meher Baba]

**Comment by xfra35** [comment]
We decided to `urldecode` the whole `PATH` in order to decode UTF-8 characters:

* `/page/%C3%BCber-uns` => `/page/über-uns`
* `/page/%D0%BA%D1%82%D0%BE-%D0%BC%D1%8B` => `/page/кто-мы`
* `/page/%E4%B8%AD%E5%9B%BD` => `/page/中国`

Cf. https://github.com/bcosca/fatfree-core/pull/71

Decoding only `PARAMS` didn't allow to define simple routes with an URI containing UTF-8 characters, such as:
```php
$f3->route('GET /page/über-uns','Foo->bar');
```

Now the reason why your issue didn't come up earlier is because tokens that might contain slashes are usually caught with a wildcard:
```php
$f3->route('POST /ajax/read/@db_object/@column/* [ajax]', 'Ajax->read');
```

So we need to decide:
* either we make it clear that route tokens should never contain slashes, even encoded. After all, @bcosca [once](https://github.com/bcosca/fatfree/issues/207#issuecomment-11648544) wrote that it used to be the case in `2.x`
* or we replace the call to `urldecode` with something that would decode everything but slashes

**Comment by stehlo** [comment]
My issue didn't come up earlier because my client resumed the project after some while, and I used originally an older version of F3 at the beginning of the given project.

--

Well, I see the reasoning.

**However, not knowing how to do this properly can't justify doing it in a wrong way.**

Also, the following suggestion is a no-go:
```php
$f3->route('POST /ajax/read/@db_object/@column/* [ajax]', 'Ajax->read');
```

Because, my next route is:
```php
$f3->route('POST /ajax/read/@db_object/@column/@value/@column2/@value2 [ajax]', 'Ajax->read');
```

--

You have proposed two options as the way forward:

1. Prohibiting valid characters is not a good idea. What's the point of it? Just to show that we don't know how to do it better?

2. Again, why to single out just the slashes?

--

But you are forgetting about the third option that wasn't mentioned:

*[TODO: I am working on it. It will appear here later today.]*

**Comment by xfra35** [comment]
> Prohibiting valid characters is not a good idea. What's the point of it? Just to show that we don't know how to do it better?

I don't know. I was just wondering if there couldn't be some side effects of allowing encoded slashes. Not all frameworks allow it and Apache [forbids](http://httpd.apache.org/docs/current/mod/core.html#allowencodedslashes) it by default.

> Again, why to single out just the slashes?

Precisely because they are used as path segment separators.

> But you are forgetting about the third option that wasn't mentioned and which is a very light-weight and by far the most superior solution

I find this solution heavier than just processing the raw `PATH` properly.

Here are two suggestions for decoding UTF-8 characters while preserving encoded slashes:

```php
// solution #1 (case sensitive)
$req=urldecode(str_replace(['%2f','%2F'],['%252f','%252F'],$this->hive['PATH']));
// solution #2 (case insensitive)
$req=implode('/',array_map(function($str){return str_replace('/','%2f',urldecode($str));},explode('/',$this->hive['PATH'])));
```

**Comment by stehlo** [comment]
I can't speak about Apache web server because I don't use it for every project. There are many other web servers.

> Precisely because they are used as path segment separators.

What if we need to preserve also other encoded characters.

> I find this solution heavier than just processing the raw `PATH` properly.

That was my point in my previous long post. It is not **proper**.

Proper is given by the meaning of this word, i.e. done in the right way.

The proposed solutions feel like an afterthought, or a hack. Circumventing the real and right solution, as if you were scared of doing it well in the first place for some reason. And why? To save a few microseconds of processing time?

If indeed this is the problem, let's have a look at this https://github.com/bcosca/fatfree/issues/1030 (unoptimised and overcomplicated regexp – just for the sake of providing syntactic sugar to lazy bums) and then we can talk about heavy solutions. (At least my correct solutions is not at the cost of performance.)

By the way, many things in F3 are becoming this way — half-baked afterthoughts — caused by insufficient efforts in the design phase.

**Comment by ikkez** [comment]
Overzealous URL **encoding** in a pre-process can also cause issues. I think the ROUTES should be kept as decoded values because it is more exact to compare the final UTF8 strings than urlencoded strings that might be built differently, i.e. a space char could be `+` or `%20`. Patching `PATH` and `PARAMS` looks good to me.

**Comment by eazuka** [comment]
@stehlo i have followed your most recent comments since you started posting yesterday on various F3 issues and commits and i most say you need to watch your words. You having a well thought-out idea or a proper solution doesn't mean you should start calling others names (lazy, lazy bums, half-baked, etc). You comments has been more of aggressive in nature of which i think its totally wrong.

You have a better idea or solution, propose it, i'm sure it will be considered by the core team because at the end, it makes the framework better. But your aggressive and harsh method isn't a way to relate in a settings like this.

**Comment by stehlo** [comment]
@ikkez I don't think that your worry is relevant because it is just theoretical. Could you tell me how a route parts could contain spaces in F3?

Regarding the patching, I don't agree.

Bong @bcosca , what do you think? Is it OK to continue the practice of incorrect solutions and implementation of afterthoughts?

**Comment by stehlo** [comment]
@eazuka Should I even waste my breath on responding to your statement?

I have been around for many years – primarily in silence toward public, especially because of commentators, like yourself, who hypocritically pay attention to **how** instead of **what**.

@ikkez Christian, this is exactly what I meant. That's the reason why I always prefer to communicate in private – to avoid futile off-topic discussions with various irrelevant people. In spite of what you kindly asked me yesterday, I shall be forced to return to my practice of deleting my posts within one or two days after posting.

**Comment by KOTRET** [comment]
You
* are <s>complaining</s> ranting about things that are done in 2015 (!)
* did not read the update documentations
* did not vetoed the commits in a timely manner

And now after a year you complain that something is not working anymore?
Beside some *imho* discussable commits (note that you *did not* participated!) and the issue itself - reduced to the fact that an percent-encoded slash is decoded - there is nothing substantially left.

Open source lives from communication, reporting bugs and creating more testcases stabilizes the project. 

If the author makes a decision, you should try to understand the intention and after that add your points against. Its easy to criticize but hard to make things better.

**Comment by xfra35** [comment]
Since @stehlo has removed half of the conversation, I moved the topic to #216.
