### ISSUE TITLE
Cache->set() ignores new TTL for already cached values

### ISSUE THREAD

**Issue by Rayne** [bcosca/fatfree-core#237]
https://github.com/bcosca/fatfree-core/blob/1b11e2052a7767e4a6a609ff6eb6c7677633d82a/base.php#L2457-L2464

The `Cache` class replaces the current timestamp `$time` and the provided `$ttl` with a cached timestamp and its cached `$ttl` value. This looks like a bug to me as it's possible to replace cached data but it's impossible to set a new TTL. Even worse its reuse of the old timestamp could lead to too short-lived (see example below) or too long-lived (when trying to set a shorter TTL) caching.

**Example**

I have tested the problem with an example (only slightly modified) provided by @exodus4d in our [Slack workspace](https://fatfreeframework-slack.herokuapp.com).

```php
/** @var Base $f3 */
$f3->CACHE = 'folder=' . __DIR__ . '/CACHE/';

$f3->route('GET *', function (Base $f3) {
    $counter = (int) $f3->get('counter');

    $f3->set('counter', ++$counter, 10);

    var_dump([
        'counter' => $f3->get('counter'),
    ]);
});

$f3->run();
```

**Expected**

When visiting the defined route every second for some minutes the `$counter` should steadily increase. Not visiting the route for 10 or more seconds would reset the counter.

**Actual**

The counter gets reseted every 10 seconds, even when accessing the route every second.

**Comment by Rayne** [comment]
According to the [documentation](https://fatfreeframework.com/3.6/base#set) this is the expected behaviour of `Base->set()` (which utilises `Cache->set()`).

> If the $ttl parameter is > 0, and the framework cache engine is enabled, the specified variable will be cached for $ttl seconds. Already cached vars will be updated by reusing the old expiration time.

The [documentation of `Case->set()`](https://fatfreeframework.com/3.6/cache#set) says only the following:

> If $ttl is 0 then the entry is saved for an infinite time. Otherwise, the specified time, in seconds, is used as TTL.

What is the reason to reuse the old timestamp and old TTL? Is there a caching backend which depends on the old information?

_The "solution" or workaround for the posted example code would be to call `Base->clear()` or `Cache->clear()` after loading data from the cache._

**Comment by ikkez** [comment]
The code looks very intentional too me.. so it's probably more a feature than a bug, but I can understand that it might lead to counterintuitive behaviour. At least it's easy to fix in the application, but we can also tihnk about altering this behaviour.. the question is: how often would you need to update a cache entry and retain its TTL, VS. setting even a newer TTL when the cache entry was touched anyways.

**Comment by Rayne** [comment]
I *personally* would always update the timestamp and TTL values to guarantee that the cached entry will be alive from "here and now" until `now + TTL` is reached. This behaviour would respect the timestamp of the call and the latest `$ttl` argument.

I would propose to not change the behaviour to avoid breaking the backwards compatibility and close the issue with a `WONTFIX` flag. Afterwards we should improve the documentation of `Cache->set()`.

**Comment by exodus4d** [comment]
I agree with @Rayne changing the behavior will definitely break existing code (including mine). 

Update the docs and make it more obvious, how `$tll` works when changing already cached vars will help.

**Comment by githubanonym** [comment]
i tried the latest version of f3 and it's seems the modification was made : https://github.com/bcosca/fatfree-core/commit/e3ddb8399f90af6135cb718b8f124eb912e6c599#diff-22b1ffa797ed0997a20765c7cf8a6549

i prefered the historical behavior (i built my website around this behavior) 
so know i cannot upgrade to the latest version of f3 !
poor framework !

was it not possible to add a parameter in order to have both behaviors ?

**Comment by Rayne** [comment]
Thanks

**Comment by githubanonym** [comment]
Maybe you could add an "update" methode to the cache that do not take ttl as a parameter ?
