### ISSUE TITLE
Wildcard vhosts on Nginx and the hive HOST key dont behave.

### ISSUE THREAD

**Issue by ethanpil** [bcosca/fatfree-core#245]
Had an issue a few days ago where I migrated an old project onto Nginx. The configuration for the project is a wildcard vhost. Had it running in apache fine for a few years and replicated the configuration in nginx. 

The nginx conf file for the vhost looks something like this ` server *.domain.com {...`

In my F3/PHP code, I parse out the subdomain from `$f3->get('HOST')` and take a specific action. After the change this stopped working.  Seems that I was getting `*.domain.com` as the return value for `$f3->get('HOST')` instead of `sub.domain.com`

Ended up changing my code to parse from `$_SERVER['HTTP_HOST']`  instead  of `$f3->get('HOST')` 

I can submit a PR but I figured it warrants some discussion here. Not sure the right thing to do. Maybe we should add one more key to retain backward compatibility?

**Comment by xfra35** [comment]
There was already a discussion about this: https://github.com/bcosca/fatfree/issues/520

`HTTP_HOST` can't be trusted by the framework because it's coming from the client while `SERVER_NAME` is coming from the server.

So you should fix `SERVER_NAME`.

You can do it :

* at Nginx level: https://serverfault.com/a/650561

* at PHP level:
```php
$_SERVER['SERVER_NAME'] = $_SERVER['HTTP_HOST'];
$f3 = require('lib/base.php');
// etc.
```
