### ISSUE TITLE
Support mixed 'strong' and 'italic' form in the Markdown processor

### ISSUE THREAD

**Issue by Jiab77** [bcosca/fatfree-core#276]
Hello and sorry to disturbing.

If I've understood correctly the code from file `/lib/markdown.php`, to process **strong** and _italic_ you're counting the recurrence of '_' and '*' characters but you can't mix them, I mean use `**_word_**` and get `<strong><em>word</em></strong>` in return.

So is there a way to support the mixed form?

It took me times to understand the regex used in the code with the website regex101 but I'm lacking skills to support the "mixed" way...

**Comment by xfra35** [comment]
What you're saying is that, even though the forms `***word***` and `___word___` are supported, the mixed forms `*__word__*`, `**_word_**`, `_**word**_` and `__*word*__` should also be supported. Right?

Then the regex should be modified so that, instead of having `\1` matching the first group in *direct order*, it should match it in *reverse* order.

Here's a fix proposal:

```php
$str=preg_replace_callback(
    '/(?<=\s|^)(?<!\\\\)([*_])([*_]?)([*_]?)(.*?)(?!\\\\)\3\2\1(?=[\s[:punct:]]|$)/',
    function($expr) {
        if ($expr[3])
            return '<strong><em>'.$expr[4].'</em></strong>';
        if ($expr[2])
            return '<strong>'.$expr[4].'</strong>';
        return '<em>'.$expr[4].'</em>';
    },
    preg_replace(
        '/(?<!\\\\)~~(.*?)(?!\\\\)~~(?=[\s[:punct:]]|$)/',
        '<del>\1</del>',
        $tmp=$str
    )
);
```

**Comment by exodus4d** [comment]
Hint: I had some similar issues recently (parsing MarkDown e.g. from GitHub with _F3s_ Markdown parser).
I replaced the parsing function with a API call to GitHubs API: https://developer.github.com/v3/markdown/ . Maybe this API response could also be used in _F3_ for validation or testing the F3 parser.
