### ISSUE TITLE
Mapper Object is not JSON Serializable :-(

### ISSUE THREAD

**Issue by n0nag0n** [bcosca/fatfree-core#311]
Just when working on a project, if you go to serialize the mapper object you end up with `"{}"`, which needless to say, made me a little sad.

I'm not terribly crazy about a new method for serializing to json such as `$mapper_ob->toJson();` cause I'd really just like to do `json_encode($mapper_ob);` or `json_encode($mapper_ob_collection);` (from `find()` method), but instead what about the following solution?

[https://stackoverflow.com/a/4697671/721019](https://stackoverflow.com/a/4697671/721019)

We could simple change `cursor.php` to the following:
```php
abstract class Cursor extends \Magic implements \IteratorAggregate, JsonSerializable {

    // code

    public function jsonSerialize() {
        return $this->cast();
    }
}
```

Thoughts and feels?

**Comment by Rayne** [comment]
This would introduce a hard dependency on JSON. According to the documentation, JSON should be enabled by default.

>  As of PHP 5.2.0, the JSON extension is bundled and compiled into PHP by default.

There is a user that states that CentOS (and probably Red Hat) is not compiling PHP with the JSON extension. I haven't checked if this statement is true. I assume that most real-world setups are shipping the JSON extension.

**Comment by n0nag0n** [comment]
Aye, it would. As far as I know, I use CentOS extensively and whenever I install php-json by hand. It doesn't look like it's included in php-common [here](https://centos.pkgs.org/7/ius-x86_64/php71u-common-7.1.30-1.el7.ius.x86_64.rpm.html) and [here](https://centos.pkgs.org/8/centos-appstream-x86_64/php-common-7.3.20-1.module_el8.2.0+498+4deef2f1.x86_64.rpm.html), but I feel like it's so defacto now that installing php-json is really common. Especially if you are installing Fat-Free for an API backend. I don't think requiring it as a hard dependency would ruffle as many feathers as say iocube, igbinary, or Mail_Parse would.

**Comment by KOTRET** [comment]
Mhm… what exactly is the targeted aim when implementing this interface?
This way we have a JSON-compatible representation of the entity, but the way back (entity &rarr; cursor) is not available (what i'd expect when working with serialization). For me there is a difference in serializing the cursor or the underlying entity.

In general, serializing objects will transform the object and all its information in a serialized form in order to persist it somehow. After deserializing, all non-serializable resources need to be wired up again and then you can work with the object in the same way as before. This requirement is not fulfilled by just casting the mapped entity.

Imho you need to call `json_encode($mapper_ob->cast())` instead.

**Comment by n0nag0n** [comment]
Yeah I guess more of what I'm going after is a JSON decoder, not a serializer. JSON doesn't really have a proper deserializer [https://www.php.net/manual/en/book.json.php](https://www.php.net/manual/en/book.json.php) so it makes me wonder if this should have been more of a `jsonDecoder` class than a `jsonSerializer` class, nor does it look like there is an out of the box implementation to re-serialize what was serialized.

I feel like I need a bowl of Lucky Charms now...
