### ISSUE TITLE
Enhancement Request - "CORS headers set for a specific route" wherever you call $f3->set('CORS.x', '');

### ISSUE THREAD

**Issue by AndrewEQ** [bcosca/fatfree-core#80]
Can we allow developers more flexibility by allowing them to set the CORS when they want to(set()) as well as globally(run())? 

From the vanilla php CORS examples floating around the net, you get the feeling that you should be able to do something like check the HEADERS.Origin (probably against a white list) and then allow the origin on a specific route when you need it, without too much fuss.

What would be great is being able to set CORS in:
- global (index.php)
- a before_route in a base controller
- a before_route in a controller
- a specific routes function
- *other - I'm probably missing someone elses' use case but you get the idea

**Comment by ikkez** [comment]
> *  a before_route in a base controller
> *  a before_route in a controller
> *  a specific routes function

I don't think that this is possible, because of the CORS preflight Options request that will never reach your controller or route function, and therefore ends in a failed cross-domain request. The router builds the appropriate preflight response (`Access-Control-Allow-Methods` etc.) according to the registered f3 routes (seamless framework integration). That's why you need to set it before.

**Comment by AndrewEQ** [comment]
Ok then, how about a "CORS function" defined in the route()?

So if it were in a routes config (http://fatfreeframework.com/framework-variables#[routes]), then it could be defined something like so:

```
[routes]
GET /=home
GET /chat/room/@name=Chat->room, 0, 0, Chat->roomCORS
```
